# ?? ??? ?? ??
spring:
  servlet:
    multipart:
      # ?? ?? ?? (???? ??? ?? ???? ?? ??)
      location: C:/lecture/uploadFiles
      max-file-size: 10MB
      # ?? ?? ?? ??
      max-request-size: 10MB